local Config = require(script.Parent.Config)

local function studsPerSecond(mph)
	return math.floor(mph * Config.Bike.MphToStuds + 0.5)
end

local Bikes = {
	harbor_100 = {
		Id = "harbor_100",
		DisplayName = "Harbor SX-E",
		StyleTag = "Compact e-dirt",
		UnlockType = "Free",
		Price = 0,
		GamePassId = 0,
		Tier = 1,
		TopSpeedMph = 34,
		TopSpeedStuds = studsPerSecond(34),
		Acceleration = 0.92,
		Handling = 0.95,
		Jump = 0.88,
		Durability = 0.95,
		IllegalOnStreet = false,
		PoliceHeatMultiplier = 1,
		Description = "Compact battery-box ripper with a slim silhouette inspired by lightweight modern e-dirt bikes. Stable, easy to read, and perfect for a first ride.",
		Paint = Color3.fromRGB(242, 152, 53),
	},
	row_125 = {
		Id = "row_125",
		DisplayName = "Rowline TR-E",
		StyleTag = "Tall trail e-moto",
		UnlockType = "Free",
		Price = 0,
		GamePassId = 0,
		Tier = 1,
		TopSpeedMph = 38,
		TopSpeedStuds = studsPerSecond(38),
		Acceleration = 1.0,
		Handling = 0.9,
		Jump = 0.92,
		Durability = 0.9,
		IllegalOnStreet = false,
		PoliceHeatMultiplier = 1,
		Description = "Taller front end, longer seat, and sharper stance for riders who want a more moto-scale electric dirt bike feel right out of the gate.",
		Paint = Color3.fromRGB(215, 70, 70),
	},
	greenway_140 = {
		Id = "greenway_140",
		DisplayName = "Greenway MX-E",
		StyleTag = "Freeride e-dirt",
		UnlockType = "Free",
		Price = 0,
		GamePassId = 0,
		Tier = 1,
		TopSpeedMph = 36,
		TopSpeedStuds = studsPerSecond(36),
		Acceleration = 0.87,
		Handling = 1.02,
		Jump = 1.0,
		Durability = 0.84,
		IllegalOnStreet = false,
		PoliceHeatMultiplier = 1,
		Description = "Lighter freeride setup with quick steering, a slim tail, and the best hop response in the free lineup.",
		Paint = Color3.fromRGB(73, 184, 104),
	},
	druid_250 = {
		Id = "druid_250",
		DisplayName = "Druid XR-E",
		StyleTag = "Performance e-dirt",
		UnlockType = "Cash",
		Price = 2800,
		GamePassId = 0,
		Tier = 2,
		TopSpeedMph = 46,
		TopSpeedStuds = studsPerSecond(46),
		Acceleration = 1.08,
		Handling = 0.96,
		Jump = 1.06,
		Durability = 1.0,
		IllegalOnStreet = false,
		PoliceHeatMultiplier = 1.05,
		Description = "Mid-tier electric dirt machine with stronger pull, better landings, and a more premium race-bike chassis.",
		Paint = Color3.fromRGB(59, 138, 230),
	},
	canal_runner = {
		Id = "canal_runner",
		DisplayName = "Canal SM-E",
		StyleTag = "Street-mod e-supermoto",
		UnlockType = "Cash",
		Price = 5200,
		GamePassId = 0,
		Tier = 3,
		TopSpeedMph = 58,
		TopSpeedStuds = studsPerSecond(58),
		Acceleration = 1.16,
		Handling = 1.04,
		Jump = 1.08,
		Durability = 0.98,
		IllegalOnStreet = true,
		PoliceHeatMultiplier = 1.2,
		Description = "Street-modded electric stunt build with 17-ish wheel attitude, fast transitions, and a bigger arrest profile.",
		Paint = Color3.fromRGB(137, 112, 232),
	},
	iron_450 = {
		Id = "iron_450",
		DisplayName = "Iron Apex 450E",
		StyleTag = "Race e-dirt",
		UnlockType = "Cash",
		Price = 9000,
		GamePassId = 0,
		Tier = 4,
		TopSpeedMph = 68,
		TopSpeedStuds = studsPerSecond(68),
		Acceleration = 1.22,
		Handling = 0.9,
		Jump = 1.12,
		Durability = 1.15,
		IllegalOnStreet = true,
		PoliceHeatMultiplier = 1.3,
		Description = "Heavy-hitting race-tuned electric dirt bike with long-travel stance, stronger torque, and late-game speed.",
		Paint = Color3.fromRGB(255, 214, 74),
	},
	shoreline_rr = {
		Id = "shoreline_rr",
		DisplayName = "Shoreline RR-E",
		StyleTag = "High-voltage race build",
		UnlockType = "Cash",
		Price = 14500,
		GamePassId = 0,
		Tier = 5,
		TopSpeedMph = 80,
		TopSpeedStuds = studsPerSecond(80),
		Acceleration = 1.3,
		Handling = 0.94,
		Jump = 1.1,
		Durability = 1.08,
		IllegalOnStreet = true,
		PoliceHeatMultiplier = 1.45,
		Description = "Top-end high-voltage race chassis with a stretched silhouette for long fast runs and big transfers.",
		Paint = Color3.fromRGB(248, 248, 248),
	},
	blue_line = {
		Id = "blue_line",
		DisplayName = "Blue Line Interceptor E",
		StyleTag = "Premium pursuit special",
		UnlockType = "Gamepass",
		Price = 0,
		GamePassId = 0,
		Tier = 4,
		TopSpeedMph = 72,
		TopSpeedStuds = studsPerSecond(72),
		Acceleration = 1.2,
		Handling = 1.05,
		Jump = 1.02,
		Durability = 1.05,
		IllegalOnStreet = true,
		PoliceHeatMultiplier = 1.35,
		Description = "Premium electric pursuit-inspired special with sharper handling and a clean blue-black commuter-race silhouette.",
		Paint = Color3.fromRGB(54, 163, 255),
	},
}

return Bikes
